name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install and Build 
        run: |
          sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
          curl -L https://nixos.org/nix/install | sh
          source $HOME/.nix-profile/etc/profile.d/nix.sh
          ./scripts/build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
